name: bandy
networks:
  web:
    external: true
    name: web
  internal: {}
volumes:
  bandy_db_data: {}
services:
  bandy-mysql:
    image: mariadb:11.4
    container_name: bandy-mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme-root}
      MARIADB_DATABASE: ${WP_DB_NAME:-wordpress}
      MARIADB_USER: ${WP_DB_USER:-wordpress}
      MARIADB_PASSWORD: ${WP_DB_PASSWORD:-wordpress}
    networks:
    - internal
    volumes:
    - bandy_db_data:/var/lib/mysql
    healthcheck:
      test:
      - CMD-SHELL
      - if command -v mariadb-admin >/dev/null 2>&1; then mariadb-admin ping -hbandy-mysql
        -uroot -p$$MARIADB_ROOT_PASSWORD --silent; else mysqladmin ping -hbandy-mysql
        -uroot -p$$MARIADB_ROOT_PASSWORD --silent; fi
      interval: 5s
      timeout: 3s
      retries: 90
      start_period: 90s
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: '3'
  bandy-fpm:
    image: wordpress:php8.3-fpm-alpine
    container_name: bandy-fpm
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: bandy-mysql:3306
      WORDPRESS_DB_NAME: ${WP_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WP_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD:-wordpress}
      WORDPRESS_CONFIG_EXTRA: 'define(''WP_ENVIRONMENT_TYPE'', ''local'');

        define(''WP_DEBUG'', true);

        define(''WP_DEBUG_LOG'', true);

        define(''WP_DEBUG_DISPLAY'', false);

        define(''SCRIPT_DEBUG'', true);

        define(''DOMAIN_CURRENT_SITE'', ''${WP_DOMAIN:-bandyforbundet.localhost}'');

        define(''WP_HOME'',''https://${WP_DOMAIN:-bandyforbundet.localhost}'');

        define(''WP_SITEURL'',''https://${WP_DOMAIN:-bandyforbundet.localhost}'');

        '
    volumes:
    - ./:/var/www
    depends_on:
      bandy-mysql:
        condition: service_healthy
    networks:
    - internal
    expose:
    - '9000'
    healthcheck:
      test:
      - CMD-SHELL
      - php -v >/dev/null 2>&1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: '3'
  bandy-nginx:
    image: nginx:1.27-alpine
    labels:
    - traefik.enable=true
    - traefik.docker.network=web
    - traefik.http.routers.bandy.entrypoints=websecure
    - traefik.http.routers.bandy.tls=true
    - traefik.http.services.bandy.loadbalancer.server.port=80
    - traefik.http.routers.bandy.rule=Host(`bandyforbundet.espenmunthe.com`)
    - traefik.http.routers.bandy.tls.certresolver=le
    container_name: bandy-nginx
    restart: unless-stopped
    volumes:
    - ./:/var/www
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - bandy-fpm
    networks:
    - web
    - internal
  bandy-cli:
    image: wordpress:cli
    container_name: bandy-cli
    depends_on:
      bandy-fpm:
        condition: service_started
    working_dir: /var/www/html
    entrypoint:
    - bash
    - -lc
    command: '"wp core version || true"

      '
    volumes:
    - ./:/var/www
    environment:
      WORDPRESS_DB_HOST: bandy-mysql:3306
      WORDPRESS_DB_NAME: ${WP_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WP_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD:-wordpress}
    networks:
    - internal
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: '3'
