[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/certs/bandyforbundet.localhost+5.pem"
    keyFile  = "/etc/traefik/certs/bandyforbundet.localhost+5-key.pem"

[tls.stores]
  [tls.stores.default.defaultCertificate]
    certFile = "/etc/traefik/certs/bandyforbundet.localhost+5.pem"
    keyFile  = "/etc/traefik/certs/bandyforbundet.localhost+5-key.pem"